site_name: Hacking Doméstico
theme:
    name: "material"

nav:
    - "Index": index.md
    - "Introducción": introduccion.md
    - "Preparando el arsenal": raspberry.md
    - "Recolección de información": informationGathering.md
    - "Analizando las redes Wifi": vulnerabilities.md
    - "Cracking de  redes Wifi": crackingWifi.md
    - "Explorando la red interna": networkAttack.md
    - "POC: Inyectando Javascript Malicioso": javascript.md
dev_addr: '0.0.0.0:8000'
