site_name: Hacking Doméstico
theme:
    name: "material"

nav:
    - "Index": index.md
    - "Introducción": introduccion.md
    - "Preparando el arsenal": raspberry.md
    - "Recolección de información": informationGathering.md
    - "Analizando las redes Wifi": vulnerabilities.md
    - "Ataques en redes Wifi": crackingWifi.md
    - "Ataques en la red interna": networkAttack.md
